run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags: []

linters:
  default: none
  enable:
    - revive
    - asciicheck
    - copyloopvar
    - cyclop
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - funlen
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    # for "public interface + private struct implementation" cases only!
    - exported func .* returns unexported type .*, which can be annoying to use
    # can be removed in the development phase
    # - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # not for the active development - can be removed in the stable phase
    - should have a package comment
    - don't use an underscore in package name
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    - should check returned error before deferring
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
    - \.pb\.goclay\.go$
    - .*/mocks/.*\.go$

linters-settings:
  ireturn:
    allow:
      - error
      - "p2p-message-service/internal/service.WebSocketManager"
    allow-pkg: ["p2p-message-service/internal/service"]
  exhaustive:
    default-signifies-exhaustive: true
