// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/myszqua/vaultify/vault/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AppRoleLogin provides a mock function for the type MockClient
func (_mock *MockClient) AppRoleLogin(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AppRoleLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_AppRoleLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppRoleLogin'
type MockClient_AppRoleLogin_Call struct {
	*mock.Call
}

// AppRoleLogin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) AppRoleLogin(ctx any) *MockClient_AppRoleLogin_Call {
	return &MockClient_AppRoleLogin_Call{Call: _e.mock.On("AppRoleLogin", ctx)}
}

func (_c *MockClient_AppRoleLogin_Call) Run(run func(ctx context.Context)) *MockClient_AppRoleLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_AppRoleLogin_Call) Return(err error) *MockClient_AppRoleLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_AppRoleLogin_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_AppRoleLogin_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type MockClient
func (_mock *MockClient) HealthCheck(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockClient_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) HealthCheck(ctx any) *MockClient_HealthCheck_Call {
	return &MockClient_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockClient_HealthCheck_Call) Run(run func(ctx context.Context)) *MockClient_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_HealthCheck_Call) Return(err error) *MockClient_HealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_HealthCheck_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// K8SLogin provides a mock function for the type MockClient
func (_mock *MockClient) K8SLogin(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for K8SLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_K8SLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'K8SLogin'
type MockClient_K8SLogin_Call struct {
	*mock.Call
}

// K8SLogin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) K8SLogin(ctx any) *MockClient_K8SLogin_Call {
	return &MockClient_K8SLogin_Call{Call: _e.mock.On("K8SLogin", ctx)}
}

func (_c *MockClient_K8SLogin_Call) Run(run func(ctx context.Context)) *MockClient_K8SLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_K8SLogin_Call) Return(err error) *MockClient_K8SLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_K8SLogin_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_K8SLogin_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function for the type MockClient
func (_mock *MockClient) ListSecrets(ctx context.Context) (*models.Response, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 *models.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.Response, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.Response); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockClient_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) ListSecrets(ctx any) *MockClient_ListSecrets_Call {
	return &MockClient_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx)}
}

func (_c *MockClient_ListSecrets_Call) Run(run func(ctx context.Context)) *MockClient_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_ListSecrets_Call) Return(response *models.Response, err error) *MockClient_ListSecrets_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockClient_ListSecrets_Call) RunAndReturn(run func(ctx context.Context) (*models.Response, error)) *MockClient_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ReadSecret provides a mock function for the type MockClient
func (_mock *MockClient) ReadSecret(ctx context.Context, path string) (*models.Response, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadSecret")
	}

	var r0 *models.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Response, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Response); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ReadSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadSecret'
type MockClient_ReadSecret_Call struct {
	*mock.Call
}

// ReadSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockClient_Expecter) ReadSecret(ctx any, path any) *MockClient_ReadSecret_Call {
	return &MockClient_ReadSecret_Call{Call: _e.mock.On("ReadSecret", ctx, path)}
}

func (_c *MockClient_ReadSecret_Call) Run(run func(ctx context.Context, path string)) *MockClient_ReadSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ReadSecret_Call) Return(response *models.Response, err error) *MockClient_ReadSecret_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockClient_ReadSecret_Call) RunAndReturn(run func(ctx context.Context, path string) (*models.Response, error)) *MockClient_ReadSecret_Call {
	_c.Call.Return(run)
	return _c
}
